sed -i '1i\
import androidx.compose.foundation.BorderStroke\
import androidx.compose.foundation.Canvas\
import androidx.compose.foundation.background\
import androidx.compose.foundation.border\
import androidx.compose.foundation.clickable\
import androidx.compose.foundation.layout.Arrangement\
import androidx.compose.foundation.layout.Box\
import androidx.compose.foundation.layout.Column\
import androidx.compose.foundation.layout.FlowRow\
import androidx.compose.foundation.layout.ExperimentalLayoutApi\
import androidx.compose.foundation.layout.Row\
import androidx.compose.foundation.layout.Spacer\
import androidx.compose.foundation.layout.fillMaxSize\
import androidx.compose.foundation.layout.fillMaxWidth\
import androidx.compose.foundation.layout.height\
import androidx.compose.foundation.layout.navigationBarsPadding\
import androidx.compose.foundation.layout.padding\
import androidx.compose.foundation.layout.size\
import androidx.compose.foundation.layout.width\
import androidx.compose.foundation.horizontalScroll\
import androidx.compose.foundation.rememberScrollState\
import androidx.compose.foundation.shape.CircleShape\
import androidx.compose.foundation.shape.RoundedCornerShape\
' app/src/main/java/com/example/ui/common/RichComponents.kt
